package mj.ocraptor.events;

public enum ProgressType {
  // @formatter:off
  UPDATE_MESSAGE,
  UPDATE_PERCENTAGE,
  UPDATE_PERCENTAGE_WITH_TEXT,
  GENERAL_LOADING,

  UPDATING_FILE_LIST,
  COUNTING_FILES,
  COUNTING_FILES_FINISHED,
  INDEX_FINISHED,
  FOLDER_FINISHED,

  NEW_FILE_FOUND,
  MODIFIED_FILE,
  KNOWN_FILE,

  LOOKING_FOR_MISSING_FILES,
  MISSING_FILES_REMOVED,
  THREAD_LIST_ONLY,

  STARTING,
  PAUSED,
  CANCELING
  // @formatter:on
}
