package mj.ocraptor.configuration.properties;

public enum ConfigBool {
  // *INDENT-OFF*
  INCLUDE_TEXT_FILES
  , INCLUDE_MS_WORD_FILES
  , INCLUDE_MS_POWERPOINT_FILES
  , INCLUDE_MS_EXCEL_FILES
  , INCLUDE_MS_XPS_FILES
  , INCLUDE_MS_RTF_FILES
  , INCLUDE_LO_WRITER_FILES
  , INCLUDE_LO_IMPRESS_FILES
  , INCLUDE_LO_CALC_FILES
  , INCLUDE_STANDALONE_IMAGE_FILES
  , INCLUDE_PDF_FILES
  , INCLUDE_POSTSCRIPT_FILES
  , INCLUDE_EPUB_FILES
  , INCLUDE_APPLE_PAGES_FILES
  , INCLUDE_APPLE_NUMBERS_FILES
  , INCLUDE_APPLE_KEY_FILES
  , INCLUDE_MS_PUBLISHER_FILES
  , INCLUDE_MS_ONENOTE_FILES
  , INCLUDE_HTML_FILES
  , INCLUDE_XML_FILES
  , INCLUDE_XOURNAL_FILES
  , INCLUDE_DJVU_FILES
  , INCLUDE_ARCHIVES
  , INCLUDE_EMAIL_FILES
  , INDEX_HIDDEN_FILES_AND_FOLDERS
  , ENABLE_IMAGE_OCR
  , ENABLE_BUG_REPORT_SCREENS
  , ENABLE_USER_COMMAND_STDERR
  , DEBUG_MODE
  , PRE_PROCESS_IMAGES_FOR_OCR
  , ALWAYS_REMOVE_MISSING_FILES_FROM_DB
  , PAUSE_ON_ERROR
  , NEW_FILES_NOTIFICATION_ONLY
  , INCLUDE_METADATA
  , ENABLE_ENTRY_DELETION_BY_USER
  ;
  // *INDENT-ON*
}
