/* Generated By:JavaCC: Do not edit this line. SearchStringParserConstants.java */
package mj.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SearchStringParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND_OPERATOR = 4;
  /** RegularExpression Id. */
  int OR_OPERATOR = 5;
  /** RegularExpression Id. */
  int AND_NOT_OPERATOR = 6;
  /** RegularExpression Id. */
  int FULLTEXTSEARCH = 7;
  /** RegularExpression Id. */
  int CONTENTSEARCH = 8;
  /** RegularExpression Id. */
  int METADATASEARCH = 9;
  /** RegularExpression Id. */
  int LUCENE_OPEN = 10;
  /** RegularExpression Id. */
  int LUCENE_CLOSE = 11;
  /** RegularExpression Id. */
  int LUCENE_EXPRESSION = 12;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int LUCENE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"AND\"",
    "\"OR\"",
    "\"AND NOT\"",
    "<FULLTEXTSEARCH>",
    "<CONTENTSEARCH>",
    "<METADATASEARCH>",
    "\"<\"",
    "\">\"",
    "<LUCENE_EXPRESSION>",
  };

}
