#!/bin/bash
# Current location, necessary if you execute
# the script from a different location other
# than the location of the script.
CURRENT_DIR="$(pwd)"

# script file location
SOURCE="${BASH_SOURCE[0]}"
# resolve $SOURCE until the file is no longer a symlink
while [ -h "$SOURCE" ]; do 
  SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$SCRIPT_DIR/$SOURCE" 
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

echo $CURRENT_DIR

# osascript -e 'tell app "System Events" to display dialog "'$SCRIPT_DIR'"'

"$SCRIPT_DIR"/OCRaptorCL --quiet --gui --userfolder --build-in-jre 
